### ISSUE TITLE
Having difficulty supporting Amazon ECR

### ISSUE THREAD

**Issue by hpe-ykoehler** [semantic-release-plus/semantic-release-plus#341]
Hi,

I am trying to use this plugin to push an image to our Amazon ECR docker registry, but I am having some difficulty, since our amazon ECR uses the "account" id in the url and this part normally comes from our Jenkins creds, so it can actually change...

I am unclear how I could configure the plugin in such a way that it would import the amazon ECR ID from the ENV variable and build the registry url with it:

${ECR_ACCOUNT_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com/

The above would normally receive the ACCOUNT_ID and REGION dynamically, but I failed to see how semantic-release configuration file can support that.

Also, since we may have more than one region, is there a way for the plugin to push more than once (basically to a list of registry instead of a single one?)

**Comment by JoA-MoS** [comment]
You should use the skipLogin setting and  perform the login like you normally would in your ci process.
 https://github.com/semantic-release-plus/semantic-release-plus/blob/master/packages/plugins/docker/README.md#configuration
