### ISSUE TITLE
Problem getting this package to work in Gitlab CI. Error: docker login failed

### ISSUE THREAD

**Issue by drtobbyas** [semantic-release-plus/semantic-release-plus#54]
I'm unable to get this package to work in GitLab CI. Always getting 'An error occurred while running semantic-release: Error: docker login failed'. I have set the environment variable DOCKER_USERNAME, DOCKER_PASSWORD. Still the same issue. Please help fix this.
![screenshot-gitlab com-2021 07 06-17_37_57](https://user-images.githubusercontent.com/40923477/124637231-61ecfa00-de81-11eb-9900-1796362141f2.png)

**Comment by JoA-MoS** [comment]
could you try and run  `docker login {registryUrl} -u={DOCKER_USERNAME} -p={DOCKER_PASSWORD}` replacing {registryUrl}, {DOCKER_USERNAME}, {DOCKER_PASSWORD} with the actual values and let me know the result? 

if it works locally then run the same command on your CI job and let me know the result?

I will also look to see what I can do to improve the error messaging around failed login.
